Import Debian changes 1.4.2-3build1
tdb (1.4.2-3build1) focal; urgency=medium

  * No-change rebuild to build with python3.8.

tdb (1.4.2-3) unstable; urgency=medium

  [ Jelmer Vernooĳ ]
  * Use secure URI in Homepage field.
  * Remove obsolete fields Name, Contact from debian/upstream/metadata.
  * Rely on pre-initialized dpkg-architecture variables.

  [ Debian Janitor ]
  * Update standards version to 4.4.1, no changes needed.

  [ Mathieu Parent ]
  * Build on hurd-i386 too (Closes: #759008)

tdb (1.4.2-2) unstable; urgency=medium

  * Upload to unstable

tdb (1.4.2-1) experimental; urgency=medium

  * Upload to experimental
  * New upstream version 1.4.2
    - d/watch Unpin to tdb 1.3.x
    - Drop python-tdb (Closes: #938630)
    - Update override_dh_auto_clean for Python3
    - Update debian/libtdb1.symbols

tdb (1.3.18-2) unstable; urgency=medium

  * Upload to unstable
  * Update salsa-ci.yml
  * Standards-Version: 4.4.0
  * Bump debhelper from old 11 to 12.
    - dh_install --list-missing removed in compat 12
  * Use dh_missing --fail-missing
  * d/copyright
    - s/GPL-3+/GPL-3.0+/ and s/LGPL-3+/LGPL-3.0+/
    - Move License details to end of file
    - Add waf licences
    - Add lib/replace licences

tdb (1.3.18-1) experimental; urgency=medium

  [ Mathieu Parent ]
  * Lintian:
    - Fix public-upstream-key-not-minimal
    - Add Build-Depends-Package field in d/*.symbols
    - Standards-Version: 4.3.0
  * Add Debian pipeline (debian/gitlab-ci.yml)
  * d/watch: Pin to tdb 1.3.x for now as 1.4.x drop --extra-python support
  * New upstream version 1.3.18

  [ Andreas Hasenack ]
  * d/p/40_test_transaction_expand_non_fatal.diff: refresh to get rid of fuzz
  * d/rules: cleanup more pyc files waf is leaving behind
  * d/rules: unset PYTHON, and now extra python version is 2 since 3 is default
  * d/libtdb1.symbols: added new symbols for 1.3.17 and 1.3.18
  * d/libtdb-dev.install: also install the static library

tdb (1.3.16-2) unstable; urgency=medium

  * Add debian/upstream/metadata.

tdb (1.3.16-1) unstable; urgency=medium

  * New upstream version 1.3.16 (Closes: #907187)
    - Update symbols, no change
  * d/changelog: Fix file-contains-trailing-whitespace
  * d/control: Rules-Requires-Root: no
  * d/control: Standards-Version: 4.2.1
  * d/rules: Remove dbgsym-migration in override_dh_strip

tdb (1.3.15-4) unstable; urgency=low

  * Upload to unstable

tdb (1.3.15-3) experimental; urgency=medium

  * Upload to experimental
  * Repository moved to salsa: Update Vcs-* fields
  * Fix global-files-wildcard-not-first-paragraph-in-dep5-copyright
  * Move to debhelper 11, no expected change
  * Standards-Version: 4.1.3, no change
  * Remove trailing whitespaces in debian/changelog

tdb (1.3.15-2) unstable; urgency=medium

  * Upload to sid

tdb (1.3.15-1) experimental; urgency=medium

  * New upstream version 1.3.15
    - Update symbols
  * Use https form of the copyright-format URL (Debian Policy 4.0.0)
  * Standards-Version: 4.0.0

tdb (1.3.13-2) unstable; urgency=medium

  * Upload to unstable

tdb (1.3.13-1) experimental; urgency=medium

  * New upstream version 1.3.13
    -  Update symbols (no change)
  * Remove Replaces+Conflicts: tdb-dev (<< 1.2.0-1). Wheezy has 1.2.10-2

tdb (1.3.11-2) unstable; urgency=medium

  * Use automatic debug packages (-dbgsym)
  * Mark libtdb-dev Multi-Arch: same

tdb (1.3.11-1) unstable; urgency=medium

  * New upstream release.
    - Update symbols (added tdb_storev)
  * Add me to uploaders
  * Use secure Vcs-* uris
  * Remove XS-Testsuite header in debian/control
  * Fix copyright-refers-to-symlink-license
  * Use https and verify upstream tarball from uscan
  * Add missing GPL-3+ license paragraph in debian/copyright
  * Bump standards version to 3.9.8 (no changes)
  * Enable all hardening and use DEB_*FLAGS_APPEND

tdb (1.3.9-1) unstable; urgency=medium

  * New upstream release.

tdb (1.3.8-2) unstable; urgency=medium

  [ Jelmer Vernooij ]
  * Drop '-b unstable' flag to Vcs-Git.

  [ Matthias Klose ]
  * Build Python3 bindings. Closes: #815141

  [ Jelmer Vernooij ]
  * Bump standards version to 3.9.7 (no changes).

tdb (1.3.8-1) unstable; urgency=medium

  * New upstream release.

tdb (1.3.7-1) unstable; urgency=medium

  * New upstream release.
  * debian/copyright: Fix license name uniqueness.

tdb (1.3.5-1) unstable; urgency=medium

  * Fix watch URL.
  * New upstream release.
  * Drop 01_reproducible_builds.diff: applied upstream.

tdb (1.3.4-2) unstable; urgency=medium

  * debian/rules: Pass CPPFLAGS from dpkg-buildflags onto configure,
    enabling hardening.
  * Make libtdb2-dbg Multi-Arch: same.
  * Add patch 01_reproducible_builds.diff: Make build reproducible by
    adding set dates to manpages.
  * debian/copyright: Fix paths for lib/replace.
  * debian/copyright: Add paragraph for most of tdb.

tdb (1.3.4-1) unstable; urgency=medium

  * New upstream release.

tdb (1.3.3-1) unstable; urgency=medium

  * New upstream release.
  * Update 40_test_transaction_expand_non_fatal.diff: Remove
    ignoring of tdb1-run-mutex-openflags2 test output,
    as the test was fixed upstream.

  * Add dh-python to Build-Depends.

tdb (1.3.2-1) unstable; urgency=medium

  * New upstream release.
   + Fixes __attribute__((visibility)) check to not use nested functions.
     Closes: #749986
  * Drop missing-stdbool-include.patch; now included upstream.
  * Update 40_test_transaction_expand_non_fatal.diff: Ignore tdb1-run-
    mutex-openflags2 test output, since newly added test fails on
    Debian.
  * Bump standards version to 3.9.6 (no changes).

tdb (1.3.1-1) unstable; urgency=medium

  * New upstream release.
  * Use canonical URL in Vcs-Git header.
  * Specify branch in Vcs-Git header.

tdb (1.3.0-1.1) unstable; urgency=medium

  * Non-maintainer upload.
  * Cherry-pick patch from upstream bug #10625 to fix FTBFS of
    reverse-build-deps which include <tdb.h> due to missing <stdbool.h>
    include. (Closes: #750572)

tdb (1.3.0-1) unstable; urgency=medium

  * New upstream release.

tdb (1.2.13-4) unstable; urgency=medium

  * Fix libtdb-dev architecture to not build on hurd.
  * Stop autopkgtest depending on build.

tdb (1.2.13-3) unstable; urgency=medium

  * Only build on linux-any and kfreebsd-any, since the Hurd does not
    yet support byte range locking (bug #190367).

tdb (1.2.13-2) unstable; urgency=medium

  * Allow output on standard error from python testsuite.

tdb (1.2.13-1) unstable; urgency=low

  * New upstream release.
  * Add basic autopkgtest for running python tests.
  * Change maintainer to Samba Debian maintainers, move myself to uploaders.
  * Bump standards version to 3.9.5 (no changes).
  * Fix --as-needed with waf.

tdb (1.2.12-1) unstable; urgency=low

  [ Andrew Bartlett ]
  * New upstream release.
   + Drop 08_waf_python_config integrated upstream.
   + Fixes two FTBFS bugs. Closes: #710342, #713098

  [ Jelmer Vernooij ]
  * Migrate to Git.
  * Bump standards version to 3.9.4.
  * Fix duplicate line in copyright file.
  * Use dpkg-buildflags, enabling hardening.

tdb (1.2.11-2.1) experimental; urgency=low

  * Non-maintainer upload with maintainer's agreement.
  * New upstream release.
   + Add 08_waf_python_config to cope with python-config no longer
     being a script.
   + Adapt 40_test_transaction_expand_non_fatal.diff after conflicts

tdb (1.2.10-2) unstable; urgency=high

  [ Ivo De Decker ]
  * Make transaction-expand test non-fatal. Fixes FTBFS. Closes: #674749
  * Fix version in symbols file to make lintian happy.

tdb (1.2.10-1.1) unstable; urgency=high

  * Fix version in symbols file to make lintian happy.

tdb (1.2.10-1) unstable; urgency=low

  * debian/rules: Remove unnecessary clean: target.
  * Properly clean up after building.
  * New upstream release.

tdb (1.2.9+git20120207-2) unstable; urgency=low

  * Bump standards version to 3.9.3 (no changes).
  * Use parseable format for copyright file.

tdb (1.2.9+git20120207-1) unstable; urgency=low

  * New upstream snapshot.
   + Unpacks waf sourcecode. Closes: #654509
   + Fixes build issues when IOV_MAX is not available, as is
     the case on Hurd systems. Closes: #657021

tdb (1.2.9-4) unstable; urgency=low

  * Explicitly use dh_python2.
  * Use system Python. Closes: #577435

tdb (1.2.9-3) unstable; urgency=low

  * Upload to unstable.
  * Use new style debhelper.

tdb (1.2.9-2) experimental; urgency=low

  * Add python-tdb-dbg and libtdb1-dbg packages.
  * Bump standards version to 3.9.2.
  * Use --disable-rpath-install only, simplifies testsuite running.
  * Switch from dh_pycentral to dh_python2. Closes: #617120
  * Drop transitional package tdb-dev.
  * Add support for multiarch to libtdb1.

tdb (1.2.9-1) unstable; urgency=low

  * New upstream release.

tdb (1.2.8-1) unstable; urgency=low

  * New upstream release.
   + Introduces symbol versioning.
  * Switch to python-support.
  * Run testsuite during build.
  * Link with --as-needed.

tdb (1.2.7+git20101021-1) unstable; urgency=low

  * New upstream snapshot.
   + Removes use of _PUBLIC_ from tdb.h. Closes: #600898

tdb (1.2.7-1) unstable; urgency=low

  * New upstream release.

tdb (1.2.3~git20100819-1) experimental; urgency=low

  * New upstream snapshot.
  * Bump standards version to 3.9.1 (no changes).
  * Switch to bzr.

tdb (1.2.2~git20100507-1) experimental; urgency=low

  * New upstream snapshot.
  * Build with standard system python. Closes: #577435
  * Remove `tdb_transaction_recover` symbol which was also removed upstream.
    This symbol was never intended to be public and would have been hard to
    use anyway.

tdb (1.2.1-2) unstable; urgency=low

  * Add missing build dependency on xsltproc, docbook-xsl. Closes:
    #570950

tdb (1.2.1-1) unstable; urgency=low

  * New upstream release.
   + Adds manual pages for tdb-tools. Closes: #557819
  * Use source format 3.
  * Bump standards version to 3.8.4.

tdb (1.2.0-1) unstable; urgency=low

  * New upstream release.
  * Rename tdb-dev -> libtdb-dev.
  * Bump standards version to 3.8.3.

tdb (1.1.5-2) unstable; urgency=low

  * Provide a symbols file.
  * Provide deprecated replacement of public tdb_logging_function symbol
    removed upstream without soname bump. Closes: #511011
  * Fix use of --as-needed.
  * Bump standards version to 3.8.2.

tdb (1.1.5-1) unstable; urgency=low

  * New upstream release.

tdb (1.1.4~git20090604-1) experimental; urgency=low

  * New upstream snapshot.

tdb (1.1.3-1) unstable; urgency=low

  * New upstream release.
  * Bump standards version to 3.8.1.

tdb (1.1.3~git20090221-1) unstable; urgency=low

  * New upstream snapshot.
  * Upload to unstable.
  * Link with --as-needed.

tdb (1.1.3~git20081222-2) experimental; urgency=low

  * Switch to python-central.
  * Add dummy watchfile explaining how to obtain an upstream tarball.
  * Fix version number. (Closes: #510885)
  * Bump shlibs because of newly added tdb_repack() symbol. (Closes: #510886)
  * Remove use of absolute paths per policy §6.1. (Closes: #510944)

tdb (1.1.2~git20081222-1) unstable; urgency=low

  * New upstream snapshot.

tdb (1.1.2~git20080615-1) unstable; urgency=low

  * New upstream snapshot.
  * Bump standards version to 3.8.0.

tdb (1.1.2~git20080521-1) unstable; urgency=low

  * New upstream snapshot.
  * Fix soname symlink. (Closes: #482008, Closes: #482228)

tdb (1.1.2~git20080520-1) unstable; urgency=low

  * New upstream snapshot.

tdb (1.1.1~svn26294-2) unstable; urgency=low

  * Add patch to clear spinlocks if set and opening a TDB in write mode.
    (Closes: #425716)
  * Change tdb-dev section to libdevel.

tdb (1.1.1~svn26294-1.1) unstable; urgency=low

  * Non-maintainer upload.
  * 10_include_signalh.diff (Closes: #460302).
    + Include signal.h in tdb.h.
  * Re-add manpages. (Closes: #439809).
    + Fix manpage sections.
    + Escape hyphens as minus signs.
  * Fix return value in tdb_delete.3. (Closes: #385389).
  * Add ${shlibs:Depends} on python-tdb package.

tdb (1.1.1~svn26294-1) unstable; urgency=low

  * New upstream snapshot.
  * Set Vcs-Svn field.
  * Support building twice in a row. (Closes: #442743)
  * Install SWIG file.
  * Upload to unstable.

tdb (1.1.1~svn26181-1) unstable; urgency=low

  * Set homepage field.
  * New upstream snapshot.
  * Add python-tdb package.
  * Allow Debian Maintainer uploads.

tdb (1.1.0-1) unstable; urgency=low

  * New upstream release.
  	* Removes spinlock code. (Closes: #400802)
    * References to tdb_lockkeys() were removed. (Closes: #309994)
    * Provide tdb_chain(un)lock() functions. (Closes: #412817)
  * New maintainer. (Closes: #411687)
  * Drop dependency on gdbm-dev.
  * Fix typo in copyright file. (Closes: #337506)

tdb (1.0.6-13) unstable; urgency=high

  * Closes: #307214: ctrlproxy: FTBFS: /usr/include/tdb.h:150: error:
    parse error before '*' token
  * Thanks to Wilmer van der Gaast <lintux@debian.org> for providing
    the patch to fix the above issue.
  * Closes: #290211: Improper copyright file
  * Closes: #262490: tdb_1.0.6-8_mips: FTBFS: opcode not supported on
    this processor: mips1. Spinlocks are not used on mips.

tdb (1.0.6-12) unstable; urgency=medium

  * Closes: #305771: libtdb is LGPL, rather than GPL as stated in
    copyright
  * Updated the configure file with the correct license information.
  * The binaries accompanying the library are _mostly_ marked as licensed
    under the GPL. As the effect, I'm (for now) assumming that those binaries
    that do not bear the license text are GPL-ed as well.
  * The sources have been updated from the Samba 3.0.14a release.
  * Closes: #305867: tdb fails to build on athlon64 running sarge/i386.
    Thanks to Len Sorensen <lennartsorensen@ruggedcom.com> for noticing that
    and providing the fix.

tdb (1.0.6-11) unstable; urgency=high

  * Added #include <signal.h> in tdb.h, to get the definition of
    sig_atomic_t (closes: Bug#264601)

tdb (1.0.6-10) unstable; urgency=high

  * tdbbackup is registered with the alternatives system now so that it
    does not conflict with the Samba package (closes: Bug#262605)

tdb (1.0.6-9) unstable; urgency=high

  * MIPS doesn't want to cooperate on the spinlocks. Disabling it for the
    architecture (closes: Bug#262490).

tdb (1.0.6-8) unstable; urgency=low

  * Updated the sources to their versions from the samba 3.0.5 package.
    The interface is 100% backward compatible.
  * Updated the Standards Version. No changes.
  * Enabled spinlocks for architectures that are supported (x86,sparc,
    mips,powerpc)

tdb (1.0.6-7) unstable; urgency=high

  * Updated the libtool version (closes: Bug#201928)

tdb (1.0.6-6) unstable; urgency=high

  * Bumped the standards version
  * Depends on debconf > 4.0
  * Fixed the build-time dependencies. Correctly depends on libgdbm-dev
    instead of on libgdbm1-dev (closes: Bug#199608)

tdb (1.0.6-5) unstable; urgency=low

  * Modified tdbtool.c to properly use multi-line strings
    (closes: Bug#195257)
  * Corrected the copyright file to not use the boilerplate.

tdb (1.0.6-4) unstable; urgency=high

  * made dependencies right for tdb-dev (closes: #143517)

tdb (1.0.6-3) unstable; urgency=high

  * Added the shared library module. It is needed for some packages on hppa.

tdb (1.0.6-2) unstable; urgency=high

  * Upgraded the config.guess and config.sub files (closes: #138609)

tdb (1.0.6-1) unstable; urgency=medium

  * Latest upstream (closes: #137972)

tdb (1.0.3-4) unstable; urgency=low

  * Updated config.guess and config.sub (closes: #103348)
  * Binaries in tdb-tools no longer are linked against the shared
    tdb library (closes: #102498)

tdb (1.0.3-3) unstable; urgency=low

  * Fixed incorrect dependency on tdb1

tdb (1.0.3-2) unstable; urgency=low

  * Changed the package description. Closes: #97636

tdb (1.0.3-1) unstable; urgency=low

  * Initial Release.